apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /    
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: post-microservice-ingress
  namespace: dwetter
spec:
  rules:
    - host: post.dwetter.nl
      http:
        paths:
          - backend:
              serviceName: post-microservice
              servicePort: 80
  tls:
    - hosts: 
        - post.dwetter.nl
      secretName: post-microservice-tls
status:
  loadBalancer:
    ingress:
      - {}