name: .NET Core push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
          
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build
      
      - name: Test
        run: dotnet test
